# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.dict_lists import DictLists  # noqa: F401,E501
from swagger_server import util


class DictList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, code: int=None, msg: str=None, result: List[DictLists]=None):  # noqa: E501
        """DictList - a model defined in Swagger

        :param code: The code of this DictList.  # noqa: E501
        :type code: int
        :param msg: The msg of this DictList.  # noqa: E501
        :type msg: str
        :param result: The result of this DictList.  # noqa: E501
        :type result: List[DictLists]
        """
        self.swagger_types = {
            'code': int,
            'msg': str,
            'result': List[DictLists]
        }

        self.attribute_map = {
            'code': 'code',
            'msg': 'msg',
            'result': 'result'
        }

        self._code = code
        self._msg = msg
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'DictList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DictList of this DictList.  # noqa: E501
        :rtype: DictList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this DictList.

        system return code  # noqa: E501

        :return: The code of this DictList.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this DictList.

        system return code  # noqa: E501

        :param code: The code of this DictList.
        :type code: int
        """

        self._code = code

    @property
    def msg(self) -> str:
        """Gets the msg of this DictList.

        system return news  # noqa: E501

        :return: The msg of this DictList.
        :rtype: str
        """
        return self._msg

    @msg.setter
    def msg(self, msg: str):
        """Sets the msg of this DictList.

        system return news  # noqa: E501

        :param msg: The msg of this DictList.
        :type msg: str
        """

        self._msg = msg

    @property
    def result(self) -> List[DictLists]:
        """Gets the result of this DictList.


        :return: The result of this DictList.
        :rtype: List[DictLists]
        """
        return self._result

    @result.setter
    def result(self, result: List[DictLists]):
        """Sets the result of this DictList.


        :param result: The result of this DictList.
        :type result: List[DictLists]
        """

        self._result = result
