# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EmosFirstCharts(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, area: str=None, inside: str=None, ultra: str=None):  # noqa: E501
        """EmosFirstCharts - a model defined in Swagger

        :param area: The area of this EmosFirstCharts.  # noqa: E501
        :type area: str
        :param inside: The inside of this EmosFirstCharts.  # noqa: E501
        :type inside: str
        :param ultra: The ultra of this EmosFirstCharts.  # noqa: E501
        :type ultra: str
        """
        self.swagger_types = {
            'area': str,
            'inside': str,
            'ultra': str
        }

        self.attribute_map = {
            'area': 'area',
            'inside': 'inside',
            'ultra': 'ultra'
        }

        self._area = area
        self._inside = inside
        self._ultra = ultra

    @classmethod
    def from_dict(cls, dikt) -> 'EmosFirstCharts':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EmosFirstCharts of this EmosFirstCharts.  # noqa: E501
        :rtype: EmosFirstCharts
        """
        return util.deserialize_model(dikt, cls)

    @property
    def area(self) -> str:
        """Gets the area of this EmosFirstCharts.

        area  # noqa: E501

        :return: The area of this EmosFirstCharts.
        :rtype: str
        """
        return self._area

    @area.setter
    def area(self, area: str):
        """Sets the area of this EmosFirstCharts.

        area  # noqa: E501

        :param area: The area of this EmosFirstCharts.
        :type area: str
        """

        self._area = area

    @property
    def inside(self) -> str:
        """Gets the inside of this EmosFirstCharts.

        Within two hours  # noqa: E501

        :return: The inside of this EmosFirstCharts.
        :rtype: str
        """
        return self._inside

    @inside.setter
    def inside(self, inside: str):
        """Sets the inside of this EmosFirstCharts.

        Within two hours  # noqa: E501

        :param inside: The inside of this EmosFirstCharts.
        :type inside: str
        """

        self._inside = inside

    @property
    def ultra(self) -> str:
        """Gets the ultra of this EmosFirstCharts.

        More than two hours  # noqa: E501

        :return: The ultra of this EmosFirstCharts.
        :rtype: str
        """
        return self._ultra

    @ultra.setter
    def ultra(self, ultra: str):
        """Sets the ultra of this EmosFirstCharts.

        More than two hours  # noqa: E501

        :param ultra: The ultra of this EmosFirstCharts.
        :type ultra: str
        """

        self._ultra = ultra
