# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Keyword1(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, name: str=None, time: str=None, url: str=None):  # noqa: E501
        """Keyword1 - a model defined in Swagger

        :param id: The id of this Keyword1.  # noqa: E501
        :type id: str
        :param name: The name of this Keyword1.  # noqa: E501
        :type name: str
        :param time: The time of this Keyword1.  # noqa: E501
        :type time: str
        :param url: The url of this Keyword1.  # noqa: E501
        :type url: str
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'time': str,
            'url': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'time': 'time',
            'url': 'url'
        }

        self._id = id
        self._name = name
        self._time = time
        self._url = url

    @classmethod
    def from_dict(cls, dikt) -> 'Keyword1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The keyword1 of this Keyword1.  # noqa: E501
        :rtype: Keyword1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Keyword1.

        id  # noqa: E501

        :return: The id of this Keyword1.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Keyword1.

        id  # noqa: E501

        :param id: The id of this Keyword1.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Keyword1.

        msg  # noqa: E501

        :return: The name of this Keyword1.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Keyword1.

        msg  # noqa: E501

        :param name: The name of this Keyword1.
        :type name: str
        """

        self._name = name

    @property
    def time(self) -> str:
        """Gets the time of this Keyword1.

        time  # noqa: E501

        :return: The time of this Keyword1.
        :rtype: str
        """
        return self._time

    @time.setter
    def time(self, time: str):
        """Sets the time of this Keyword1.

        time  # noqa: E501

        :param time: The time of this Keyword1.
        :type time: str
        """

        self._time = time

    @property
    def url(self) -> str:
        """Gets the url of this Keyword1.

        url file  # noqa: E501

        :return: The url of this Keyword1.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this Keyword1.

        url file  # noqa: E501

        :param url: The url of this Keyword1.
        :type url: str
        """

        self._url = url
