# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MaintainLists(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, work: str=None, order: str=None, type: str=None, ocode: str=None, code: str=None, personnel: str=None, posttime: str=None):  # noqa: E501
        """MaintainLists - a model defined in Swagger

        :param id: The id of this MaintainLists.  # noqa: E501
        :type id: int
        :param work: The work of this MaintainLists.  # noqa: E501
        :type work: str
        :param order: The order of this MaintainLists.  # noqa: E501
        :type order: str
        :param type: The type of this MaintainLists.  # noqa: E501
        :type type: str
        :param ocode: The ocode of this MaintainLists.  # noqa: E501
        :type ocode: str
        :param code: The code of this MaintainLists.  # noqa: E501
        :type code: str
        :param personnel: The personnel of this MaintainLists.  # noqa: E501
        :type personnel: str
        :param posttime: The posttime of this MaintainLists.  # noqa: E501
        :type posttime: str
        """
        self.swagger_types = {
            'id': int,
            'work': str,
            'order': str,
            'type': str,
            'ocode': str,
            'code': str,
            'personnel': str,
            'posttime': str
        }

        self.attribute_map = {
            'id': 'id',
            'work': 'work',
            'order': 'order',
            'type': 'type',
            'ocode': 'ocode',
            'code': 'code',
            'personnel': 'personnel',
            'posttime': 'posttime'
        }

        self._id = id
        self._work = work
        self._order = order
        self._type = type
        self._ocode = ocode
        self._code = code
        self._personnel = personnel
        self._posttime = posttime

    @classmethod
    def from_dict(cls, dikt) -> 'MaintainLists':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MaintainLists of this MaintainLists.  # noqa: E501
        :rtype: MaintainLists
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this MaintainLists.

        ID  # noqa: E501

        :return: The id of this MaintainLists.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this MaintainLists.

        ID  # noqa: E501

        :param id: The id of this MaintainLists.
        :type id: int
        """

        self._id = id

    @property
    def work(self) -> str:
        """Gets the work of this MaintainLists.

        workstation  # noqa: E501

        :return: The work of this MaintainLists.
        :rtype: str
        """
        return self._work

    @work.setter
    def work(self, work: str):
        """Sets the work of this MaintainLists.

        workstation  # noqa: E501

        :param work: The work of this MaintainLists.
        :type work: str
        """

        self._work = work

    @property
    def order(self) -> str:
        """Gets the order of this MaintainLists.

        Complaint number  # noqa: E501

        :return: The order of this MaintainLists.
        :rtype: str
        """
        return self._order

    @order.setter
    def order(self, order: str):
        """Sets the order of this MaintainLists.

        Complaint number  # noqa: E501

        :param order: The order of this MaintainLists.
        :type order: str
        """

        self._order = order

    @property
    def type(self) -> str:
        """Gets the type of this MaintainLists.

        Replace terminal type  # noqa: E501

        :return: The type of this MaintainLists.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this MaintainLists.

        Replace terminal type  # noqa: E501

        :param type: The type of this MaintainLists.
        :type type: str
        """

        self._type = type

    @property
    def ocode(self) -> str:
        """Gets the ocode of this MaintainLists.

        Original barcode  # noqa: E501

        :return: The ocode of this MaintainLists.
        :rtype: str
        """
        return self._ocode

    @ocode.setter
    def ocode(self, ocode: str):
        """Sets the ocode of this MaintainLists.

        Original barcode  # noqa: E501

        :param ocode: The ocode of this MaintainLists.
        :type ocode: str
        """

        self._ocode = ocode

    @property
    def code(self) -> str:
        """Gets the code of this MaintainLists.

        new barcode  # noqa: E501

        :return: The code of this MaintainLists.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this MaintainLists.

        new barcode  # noqa: E501

        :param code: The code of this MaintainLists.
        :type code: str
        """

        self._code = code

    @property
    def personnel(self) -> str:
        """Gets the personnel of this MaintainLists.

        Installation staff  # noqa: E501

        :return: The personnel of this MaintainLists.
        :rtype: str
        """
        return self._personnel

    @personnel.setter
    def personnel(self, personnel: str):
        """Sets the personnel of this MaintainLists.

        Installation staff  # noqa: E501

        :param personnel: The personnel of this MaintainLists.
        :type personnel: str
        """

        self._personnel = personnel

    @property
    def posttime(self) -> str:
        """Gets the posttime of this MaintainLists.

        use time  # noqa: E501

        :return: The posttime of this MaintainLists.
        :rtype: str
        """
        return self._posttime

    @posttime.setter
    def posttime(self, posttime: str):
        """Sets the posttime of this MaintainLists.

        use time  # noqa: E501

        :param posttime: The posttime of this MaintainLists.
        :type posttime: str
        """

        self._posttime = posttime
