# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class NoticeLists2(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, desc: str=None, posttime: str=None, title: str=None):  # noqa: E501
        """NoticeLists2 - a model defined in Swagger

        :param id: The id of this NoticeLists2.  # noqa: E501
        :type id: int
        :param desc: The desc of this NoticeLists2.  # noqa: E501
        :type desc: str
        :param posttime: The posttime of this NoticeLists2.  # noqa: E501
        :type posttime: str
        :param title: The title of this NoticeLists2.  # noqa: E501
        :type title: str
        """
        self.swagger_types = {
            'id': int,
            'desc': str,
            'posttime': str,
            'title': str
        }

        self.attribute_map = {
            'id': 'id',
            'desc': 'desc',
            'posttime': 'posttime',
            'title': 'title'
        }

        self._id = id
        self._desc = desc
        self._posttime = posttime
        self._title = title

    @classmethod
    def from_dict(cls, dikt) -> 'NoticeLists2':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NoticeLists2 of this NoticeLists2.  # noqa: E501
        :rtype: NoticeLists2
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this NoticeLists2.

        notice code  # noqa: E501

        :return: The id of this NoticeLists2.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this NoticeLists2.

        notice code  # noqa: E501

        :param id: The id of this NoticeLists2.
        :type id: int
        """

        self._id = id

    @property
    def desc(self) -> str:
        """Gets the desc of this NoticeLists2.

        notice type  # noqa: E501

        :return: The desc of this NoticeLists2.
        :rtype: str
        """
        return self._desc

    @desc.setter
    def desc(self, desc: str):
        """Sets the desc of this NoticeLists2.

        notice type  # noqa: E501

        :param desc: The desc of this NoticeLists2.
        :type desc: str
        """

        self._desc = desc

    @property
    def posttime(self) -> str:
        """Gets the posttime of this NoticeLists2.

        notice posttime  # noqa: E501

        :return: The posttime of this NoticeLists2.
        :rtype: str
        """
        return self._posttime

    @posttime.setter
    def posttime(self, posttime: str):
        """Sets the posttime of this NoticeLists2.

        notice posttime  # noqa: E501

        :param posttime: The posttime of this NoticeLists2.
        :type posttime: str
        """

        self._posttime = posttime

    @property
    def title(self) -> str:
        """Gets the title of this NoticeLists2.

        notice title  # noqa: E501

        :return: The title of this NoticeLists2.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this NoticeLists2.

        notice title  # noqa: E501

        :param title: The title of this NoticeLists2.
        :type title: str
        """

        self._title = title
