# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class NoticeData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, type: int=None, desc: str=None, title: str=None):  # noqa: E501
        """NoticeData - a model defined in Swagger

        :param type: The type of this NoticeData.  # noqa: E501
        :type type: int
        :param desc: The desc of this NoticeData.  # noqa: E501
        :type desc: str
        :param title: The title of this NoticeData.  # noqa: E501
        :type title: str
        """
        self.swagger_types = {
            'type': int,
            'desc': str,
            'title': str
        }

        self.attribute_map = {
            'type': 'type',
            'desc': 'desc',
            'title': 'title'
        }

        self._type = type
        self._desc = desc
        self._title = title

    @classmethod
    def from_dict(cls, dikt) -> 'NoticeData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NoticeData of this NoticeData.  # noqa: E501
        :rtype: NoticeData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> int:
        """Gets the type of this NoticeData.

        notice type  # noqa: E501

        :return: The type of this NoticeData.
        :rtype: int
        """
        return self._type

    @type.setter
    def type(self, type: int):
        """Sets the type of this NoticeData.

        notice type  # noqa: E501

        :param type: The type of this NoticeData.
        :type type: int
        """

        self._type = type

    @property
    def desc(self) -> str:
        """Gets the desc of this NoticeData.

        notice content  # noqa: E501

        :return: The desc of this NoticeData.
        :rtype: str
        """
        return self._desc

    @desc.setter
    def desc(self, desc: str):
        """Sets the desc of this NoticeData.

        notice content  # noqa: E501

        :param desc: The desc of this NoticeData.
        :type desc: str
        """

        self._desc = desc

    @property
    def title(self) -> str:
        """Gets the title of this NoticeData.

        notice title  # noqa: E501

        :return: The title of this NoticeData.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this NoticeData.

        notice title  # noqa: E501

        :param title: The title of this NoticeData.
        :type title: str
        """

        self._title = title
