# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Outlist(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, outman: str=None):  # noqa: E501
        """Outlist - a model defined in Swagger

        :param outman: The outman of this Outlist.  # noqa: E501
        :type outman: str
        """
        self.swagger_types = {
            'outman': str
        }

        self.attribute_map = {
            'outman': 'outman'
        }

        self._outman = outman

    @classmethod
    def from_dict(cls, dikt) -> 'Outlist':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The outlist of this Outlist.  # noqa: E501
        :rtype: Outlist
        """
        return util.deserialize_model(dikt, cls)

    @property
    def outman(self) -> str:
        """Gets the outman of this Outlist.

        the pepole for outbound  # noqa: E501

        :return: The outman of this Outlist.
        :rtype: str
        """
        return self._outman

    @outman.setter
    def outman(self, outman: str):
        """Sets the outman of this Outlist.

        the pepole for outbound  # noqa: E501

        :param outman: The outman of this Outlist.
        :type outman: str
        """

        self._outman = outman
