# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SuppliesQueryInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, work: str=None, use: str=None, receive: str=None, posttime: str=None):  # noqa: E501
        """SuppliesQueryInfo - a model defined in Swagger

        :param work: The work of this SuppliesQueryInfo.  # noqa: E501
        :type work: str
        :param use: The use of this SuppliesQueryInfo.  # noqa: E501
        :type use: str
        :param receive: The receive of this SuppliesQueryInfo.  # noqa: E501
        :type receive: str
        :param posttime: The posttime of this SuppliesQueryInfo.  # noqa: E501
        :type posttime: str
        """
        self.swagger_types = {
            'work': str,
            'use': str,
            'receive': str,
            'posttime': str
        }

        self.attribute_map = {
            'work': 'work',
            'use': 'use',
            'receive': 'receive',
            'posttime': 'posttime'
        }

        self._work = work
        self._use = use
        self._receive = receive
        self._posttime = posttime

    @classmethod
    def from_dict(cls, dikt) -> 'SuppliesQueryInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SuppliesQueryInfo of this SuppliesQueryInfo.  # noqa: E501
        :rtype: SuppliesQueryInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def work(self) -> str:
        """Gets the work of this SuppliesQueryInfo.

        workstation  # noqa: E501

        :return: The work of this SuppliesQueryInfo.
        :rtype: str
        """
        return self._work

    @work.setter
    def work(self, work: str):
        """Sets the work of this SuppliesQueryInfo.

        workstation  # noqa: E501

        :param work: The work of this SuppliesQueryInfo.
        :type work: str
        """

        self._work = work

    @property
    def use(self) -> str:
        """Gets the use of this SuppliesQueryInfo.

        use  # noqa: E501

        :return: The use of this SuppliesQueryInfo.
        :rtype: str
        """
        return self._use

    @use.setter
    def use(self, use: str):
        """Sets the use of this SuppliesQueryInfo.

        use  # noqa: E501

        :param use: The use of this SuppliesQueryInfo.
        :type use: str
        """

        self._use = use

    @property
    def receive(self) -> str:
        """Gets the receive of this SuppliesQueryInfo.

        Claimant  # noqa: E501

        :return: The receive of this SuppliesQueryInfo.
        :rtype: str
        """
        return self._receive

    @receive.setter
    def receive(self, receive: str):
        """Sets the receive of this SuppliesQueryInfo.

        Claimant  # noqa: E501

        :param receive: The receive of this SuppliesQueryInfo.
        :type receive: str
        """

        self._receive = receive

    @property
    def posttime(self) -> str:
        """Gets the posttime of this SuppliesQueryInfo.

        date time  # noqa: E501

        :return: The posttime of this SuppliesQueryInfo.
        :rtype: str
        """
        return self._posttime

    @posttime.setter
    def posttime(self, posttime: str):
        """Sets the posttime of this SuppliesQueryInfo.

        date time  # noqa: E501

        :param posttime: The posttime of this SuppliesQueryInfo.
        :type posttime: str
        """

        self._posttime = posttime
