# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Upload(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, type: int=None, url: str=None, name: str=None):  # noqa: E501
        """Upload - a model defined in Swagger

        :param type: The type of this Upload.  # noqa: E501
        :type type: int
        :param url: The url of this Upload.  # noqa: E501
        :type url: str
        :param name: The name of this Upload.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {
            'type': int,
            'url': str,
            'name': str
        }

        self.attribute_map = {
            'type': 'type',
            'url': 'url',
            'name': 'name'
        }

        self._type = type
        self._url = url
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'Upload':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Upload of this Upload.  # noqa: E501
        :rtype: Upload
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> int:
        """Gets the type of this Upload.

        type  # noqa: E501

        :return: The type of this Upload.
        :rtype: int
        """
        return self._type

    @type.setter
    def type(self, type: int):
        """Sets the type of this Upload.

        type  # noqa: E501

        :param type: The type of this Upload.
        :type type: int
        """

        self._type = type

    @property
    def url(self) -> str:
        """Gets the url of this Upload.

        file url  # noqa: E501

        :return: The url of this Upload.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this Upload.

        file url  # noqa: E501

        :param url: The url of this Upload.
        :type url: str
        """

        self._url = url

    @property
    def name(self) -> str:
        """Gets the name of this Upload.

        file name  # noqa: E501

        :return: The name of this Upload.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Upload.

        file name  # noqa: E501

        :param name: The name of this Upload.
        :type name: str
        """

        self._name = name
