# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class HighListcommunity(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, name: str=None, total: str=None):  # noqa: E501
        """HighListcommunity - a model defined in Swagger

        :param id: The id of this HighListcommunity.  # noqa: E501
        :type id: int
        :param name: The name of this HighListcommunity.  # noqa: E501
        :type name: str
        :param total: The total of this HighListcommunity.  # noqa: E501
        :type total: str
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'total': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'total': 'total'
        }

        self._id = id
        self._name = name
        self._total = total

    @classmethod
    def from_dict(cls, dikt) -> 'HighListcommunity':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HighListcommunity of this HighListcommunity.  # noqa: E501
        :rtype: HighListcommunity
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this HighListcommunity.

        ID  # noqa: E501

        :return: The id of this HighListcommunity.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this HighListcommunity.

        ID  # noqa: E501

        :param id: The id of this HighListcommunity.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this HighListcommunity.

        name  # noqa: E501

        :return: The name of this HighListcommunity.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this HighListcommunity.

        name  # noqa: E501

        :param name: The name of this HighListcommunity.
        :type name: str
        """

        self._name = name

    @property
    def total(self) -> str:
        """Gets the total of this HighListcommunity.

        total  # noqa: E501

        :return: The total of this HighListcommunity.
        :rtype: str
        """
        return self._total

    @total.setter
    def total(self, total: str):
        """Sets the total of this HighListcommunity.

        total  # noqa: E501

        :param total: The total of this HighListcommunity.
        :type total: str
        """

        self._total = total
