# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class HighListCommunityTotal(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, code: int=None, msg: str=None, total: str=None):  # noqa: E501
        """HighListCommunityTotal - a model defined in Swagger

        :param code: The code of this HighListCommunityTotal.  # noqa: E501
        :type code: int
        :param msg: The msg of this HighListCommunityTotal.  # noqa: E501
        :type msg: str
        :param total: The total of this HighListCommunityTotal.  # noqa: E501
        :type total: str
        """
        self.swagger_types = {
            'code': int,
            'msg': str,
            'total': str
        }

        self.attribute_map = {
            'code': 'code',
            'msg': 'msg',
            'total': 'total'
        }

        self._code = code
        self._msg = msg
        self._total = total

    @classmethod
    def from_dict(cls, dikt) -> 'HighListCommunityTotal':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HighListCommunityTotal of this HighListCommunityTotal.  # noqa: E501
        :rtype: HighListCommunityTotal
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this HighListCommunityTotal.

        system return code  # noqa: E501

        :return: The code of this HighListCommunityTotal.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this HighListCommunityTotal.

        system return code  # noqa: E501

        :param code: The code of this HighListCommunityTotal.
        :type code: int
        """

        self._code = code

    @property
    def msg(self) -> str:
        """Gets the msg of this HighListCommunityTotal.

        system return news  # noqa: E501

        :return: The msg of this HighListCommunityTotal.
        :rtype: str
        """
        return self._msg

    @msg.setter
    def msg(self, msg: str):
        """Sets the msg of this HighListCommunityTotal.

        system return news  # noqa: E501

        :param msg: The msg of this HighListCommunityTotal.
        :type msg: str
        """

        self._msg = msg

    @property
    def total(self) -> str:
        """Gets the total of this HighListCommunityTotal.

        total  # noqa: E501

        :return: The total of this HighListCommunityTotal.
        :rtype: str
        """
        return self._total

    @total.setter
    def total(self, total: str):
        """Sets the total of this HighListCommunityTotal.

        total  # noqa: E501

        :param total: The total of this HighListCommunityTotal.
        :type total: str
        """

        self._total = total
