# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class OutData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, work: str=None, type: str=None, model: str=None, people: str=None, code: str=None):  # noqa: E501
        """OutData - a model defined in Swagger

        :param work: The work of this OutData.  # noqa: E501
        :type work: str
        :param type: The type of this OutData.  # noqa: E501
        :type type: str
        :param model: The model of this OutData.  # noqa: E501
        :type model: str
        :param people: The people of this OutData.  # noqa: E501
        :type people: str
        :param code: The code of this OutData.  # noqa: E501
        :type code: str
        """
        self.swagger_types = {
            'work': str,
            'type': str,
            'model': str,
            'people': str,
            'code': str
        }

        self.attribute_map = {
            'work': 'work',
            'type': 'type',
            'model': 'model',
            'people': 'people',
            'code': 'code'
        }

        self._work = work
        self._type = type
        self._model = model
        self._people = people
        self._code = code

    @classmethod
    def from_dict(cls, dikt) -> 'OutData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OutData of this OutData.  # noqa: E501
        :rtype: OutData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def work(self) -> str:
        """Gets the work of this OutData.

        Workstation  # noqa: E501

        :return: The work of this OutData.
        :rtype: str
        """
        return self._work

    @work.setter
    def work(self, work: str):
        """Sets the work of this OutData.

        Workstation  # noqa: E501

        :param work: The work of this OutData.
        :type work: str
        """

        self._work = work

    @property
    def type(self) -> str:
        """Gets the type of this OutData.

        terminal type  # noqa: E501

        :return: The type of this OutData.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this OutData.

        terminal type  # noqa: E501

        :param type: The type of this OutData.
        :type type: str
        """

        self._type = type

    @property
    def model(self) -> str:
        """Gets the model of this OutData.

        Terminal model  # noqa: E501

        :return: The model of this OutData.
        :rtype: str
        """
        return self._model

    @model.setter
    def model(self, model: str):
        """Sets the model of this OutData.

        Terminal model  # noqa: E501

        :param model: The model of this OutData.
        :type model: str
        """

        self._model = model

    @property
    def people(self) -> str:
        """Gets the people of this OutData.

        Installation staff  # noqa: E501

        :return: The people of this OutData.
        :rtype: str
        """
        return self._people

    @people.setter
    def people(self, people: str):
        """Sets the people of this OutData.

        Installation staff  # noqa: E501

        :param people: The people of this OutData.
        :type people: str
        """

        self._people = people

    @property
    def code(self) -> str:
        """Gets the code of this OutData.

        Bar code  # noqa: E501

        :return: The code of this OutData.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this OutData.

        Bar code  # noqa: E501

        :param code: The code of this OutData.
        :type code: str
        """

        self._code = code
