# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UseCodess(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, code: int=None, type: str=None, model: str=None):  # noqa: E501
        """UseCodess - a model defined in Swagger

        :param code: The code of this UseCodess.  # noqa: E501
        :type code: int
        :param type: The type of this UseCodess.  # noqa: E501
        :type type: str
        :param model: The model of this UseCodess.  # noqa: E501
        :type model: str
        """
        self.swagger_types = {
            'code': int,
            'type': str,
            'model': str
        }

        self.attribute_map = {
            'code': 'code',
            'type': 'type',
            'model': 'model'
        }

        self._code = code
        self._type = type
        self._model = model

    @classmethod
    def from_dict(cls, dikt) -> 'UseCodess':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UseCodess of this UseCodess.  # noqa: E501
        :rtype: UseCodess
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this UseCodess.

        system return code  # noqa: E501

        :return: The code of this UseCodess.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this UseCodess.

        system return code  # noqa: E501

        :param code: The code of this UseCodess.
        :type code: int
        """

        self._code = code

    @property
    def type(self) -> str:
        """Gets the type of this UseCodess.

        type  # noqa: E501

        :return: The type of this UseCodess.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this UseCodess.

        type  # noqa: E501

        :param type: The type of this UseCodess.
        :type type: str
        """

        self._type = type

    @property
    def model(self) -> str:
        """Gets the model of this UseCodess.

        model  # noqa: E501

        :return: The model of this UseCodess.
        :rtype: str
        """
        return self._model

    @model.setter
    def model(self, model: str):
        """Sets the model of this UseCodess.

        model  # noqa: E501

        :param model: The model of this UseCodess.
        :type model: str
        """

        self._model = model
